apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-go-basic-r5h0
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-go-basic-r5h0
    app.kubernetes.io/part-of: e2e-golang
  name: devfile-sample-go-basic-r5h0
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: devfile-sample-go-basic-r5h0
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: devfile-sample-go-basic-r5h0
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-kvsi-tenant/e2e-golang/devfile-sample-go-basic-r5h0@sha256:d8816170e17f0c8b03cfef86c424d70586ffd6720eb94c16f5ac558a973102dd
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
